#!/bin/bash

# aicat.sh - Concatenate files with AI-friendly headers and documentation
# Usage: aicat.sh <title> <file1> <file2> ... <fileN>

# Exit on error
set -e

# Check if at least two arguments are provided (title and at least one file)
if [ $# -lt 2 ]; then
    echo "Error: Insufficient arguments"
    echo "Usage: aicat.sh <title> <file1> <file2> ... <fileN>"
    exit 1
fi

# Get the title from the first argument
TITLE="$1"
shift  # Remove the first argument (title) from the argument list

# Print AI prompt and root header
cat << EOF
<!-- 
AI READING GUIDE:
This document contains multiple configuration files concatenated together.
- The top-level header (# Title) indicates the overall combined document.
- Each second-level header (## Filename) indicates the start of a new file.
- File contents are preserved exactly as they appear in their original files.
- Please analyze each file section individually and then consider their relationships.
- Pay attention to imports, references between files, and configuration patterns.
- When making recommendations, consider the entire system structure.
- This file was generated by aicat.sh for AI analysis purposes.
-->

EOF

# Print the root header
echo "# $TITLE"
echo

# Process each file
for file in "$@"; do
    if [ ! -f "$file" ]; then
        echo "Warning: File '$file' does not exist. Skipping."
        continue
    fi
    
    # Extract the filename without path
    filename=$(basename "$file")
    
    # Add a header for the file
    echo "## $filename"
    echo
    
    # Cat the file content
    cat "$file"
    
    # Add a blank line after each file except the last one
    if [ "$file" != "${@: -1}" ]; then
        echo
        echo
    fi
done